providers = ["python"]

[phases.setup]
nixPkgs = ["python311"]
cmds = [
  "python3 -m ensurepip --upgrade"
]

[phases.install]
cmds = [
  "python3 -m pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn webapp.app:app" 